services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: docling-nginx
    expose:
      - "80"
    depends_on:
      - frontend
      - backend
    networks:
      - docling-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docling-backend
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - MAX_FILE_SIZE=52428800
      - PROCESSING_TIMEOUT=600
      - ALLOWED_ORIGINS=*
      - ENVIRONMENT=production
    expose:
      - "8080"
    volumes:
      - uploads:/app/uploads
    networks:
      - docling-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_API_URL=/api
    container_name: docling-frontend
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - NODE_ENV=production
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - docling-network
    restart: unless-stopped

volumes:
  uploads:
    driver: local

networks:
  docling-network:
    driver: bridge