# DigitalOcean App Platform Configuration
# Workshop Document Processor - Staging Environment
#
# Note: This configuration uses a self-hosted Supabase instance via Coolify
# Supabase URL: https://supabasekong-pgg8kss0oc08oo0gokgossog.app.thit.io/

name: workshop-doc-processor-staging
region: nyc3

# Frontend Service (Next.js)
services:
  - name: frontend
    github:
      repo: YOUR_GITHUB_USERNAME/workshop-document-processor
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: cd frontend && npm ci && npm run build
    
    # Run configuration
    run_command: cd frontend && npm start
    
    # Environment
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: ${backend.PUBLIC_URL}
        type: SECRET
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://supabasekong-pgg8kss0oc08oo0gokgossog.app.thit.io/
        type: SECRET
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc1OTMyNjAwMCwiZXhwIjo0OTE0OTk5NjAwLCJyb2xlIjoiYW5vbiJ9.9N2FNNrBisKwF-AIj-jdeB4pGRNNBol-kXTNL3RCBFY
        type: SECRET
      - key: NODE_ENV
        value: production
    
    # Resource allocation
    instance_size_slug: basic-xxs
    instance_count: 1
    
    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # HTTP configuration
    http_port: 3000
    
    # Routes
    routes:
      - path: /

  # Backend Service (FastAPI)
  - name: backend
    github:
      repo: YOUR_GITHUB_USERNAME/workshop-document-processor
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: cd backend && pip install --upgrade pip && pip install -r requirements.txt
    
    # Run configuration
    run_command: cd backend && uvicorn app.main:app --host 0.0.0.0 --port 8080
    
    # Environment
    envs:
      - key: SUPABASE_URL
        value: https://supabasekong-pgg8kss0oc08oo0gokgossog.app.thit.io/
        type: SECRET
      - key: SUPABASE_KEY
        value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc1OTMyNjAwMCwiZXhwIjo0OTE0OTk5NjAwLCJyb2xlIjoic2VydmljZV9yb2xlIn0.EnOpR72H05QVdHsjZPsw2IC3vSnOUcwOWd8MreYffR4
        type: SECRET
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: PROCESSING_TIMEOUT
        value: "300"
      - key: ALLOWED_ORIGINS
        value: ${frontend.PUBLIC_URL}
        type: SECRET
      - key: ENVIRONMENT
        value: staging
    
    # Resource allocation
    instance_size_slug: basic-xs
    instance_count: 1
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # HTTP configuration
    http_port: 8080
    
    # Routes
    routes:
      - path: /api

# Auto-scaling configuration (optional for staging)
# Uncomment for production deployment
# autoscaling:
#   min_instance_count: 1
#   max_instance_count: 3
#   metrics:
#     cpu:
#       percent: 80